all:
	@/usr/bin/scons -Q

# it is also possible to use
# @/usr/bin/scons -Q -j4

install:
	@/usr/bin/scons -Q install

clean:
	@/usr/bin/scons -Q -c

uninstall:
	@/usr/bin/scons -Q -c install

doc:
	@/usr/bin/scons -Q doc

dist:
	@/usr/bin/scons -Q dist-tgz

dist-tgz:
	@/usr/bin/scons -Q dist-tgz

dist-bz2:
	@/usr/bin/scons -Q dist-bz2

dist-zip:
	@/usr/bin/scons -Q dist-zip

distclean:
	@/usr/bin/scons -Q -c
	@/usr/bin/scons -Q distclean

