all:
	@/usr/bin/scons -Q

# it is also possible to use
# @/usr/bin/scons -Q -j4

install:
	@/usr/bin/scons -Q install

clean:
	@/usr/bin/scons -Q -c

uninstall:
	@/usr/bin/scons -Q -c install

dist:
	@/usr/bin/scons -Q dist

distclean:
	@/usr/bin/scons -Q -c
	@/usr/bin/scons -Q distclean

